config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  resources :chat_rooms
  resources :users
  resources :messages

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages

  def users
    User.all
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  def wait_key
    "wait_by_#{id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.find(cookies.encrypted[:user_id])
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def show
    @chat_room = ChatRoom.find(params[:id])
    @messages = @chat_room.messages.includes(:user)
    @message = Message.new
  end

  def new
    return render 'wait' if already_waiting(current_user)

    waiting_channel = Redis.current.spop('wait')
    if waiting_channel
      room = ChatRoom.create!
      ActionCable.server.broadcast waiting_channel, chat_room_path(room)
      redirect_to chat_room_path(room)
    else
      Redis.current.sadd('wait', current_user.wait_key)
      render 'wait'
    end
  end

  private

  def chat_room_params
    params.fetch(:chat_room, {})
  end

  def already_waiting(user)
    Redis.current.sismember("wait", current_user.wait_key)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    chat_room = ChatRoom.find(params[:chat_room_id])
    mes = Message.create!(message_params.merge(user: current_user, chat_room: chat_room))
    mes.broadcast_append_to chat_room, :messages, target: 'messages'
  end

  private

  def message_params
    params.require(:message)
          .permit(:content, :chat_room_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    cookies.encrypted[:user_id] = nil
  end

  def create
    @user = User.create!(user_params)
    cookies.encrypted[:user_id] = @user.id
    redirect_to new_chat_room_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(cookies.encrypted[:user_id])
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/show.html.erb
<p id="notice"><%= notice %></p>
<div class="flex flex-col">
  <nav class="px-4 py-3 text-right">
      <%= link_to "トップに戻る", root_path, class: "font-bold text-blue-600" %>
  </nav>
  <main class="w-full flex flex-col h-screen" data-controller="messages">
    <div
      data-action="turbo:before-stream-render->messages#scroll" class="overflow-auto pb-20 px-4"
      data-messages-target="messages"
    >
      <%= turbo_stream_from @chat_room, :messages %>
      <div id="messages" class="space-y-6" >
        <%= render @messages%>
      </div>
    </div>
    <div class="py-4">
      <%= render 'messages/form', message: @message %>
    </div>
  </main>
</div>

app/views/chat_rooms/wait.html.erb
相手を探しています。お待ち下さい...

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="text-gray-800">
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<div data-controller="input" >
  <div data-action="turbo:submit-start->input#clear">
    <%= form_with model: message do |f| %>
      <div class="flex w-full px-2" >
        <%= hidden_field_tag :chat_room_id, @chat_room.id %>
        <%= f.text_field :content, class: "w-full", data: {"input-target": "message"} %>
        <%= f.submit '送信', class: "text-gray-100 rounded bg-blue-600 w-20 ml-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" data-messages-target="message" class="scaffold_record">
  <div>
    <div>
      <span>
        <%= message.user.name %>
      </span>
      <span class="ml-2 text-sm text-gray-400">
        <%= message.created_at.strftime("%H:%M") %>
      </span>
    </div>
    <div class="mt-2 bg-gray-200 px-3 py-2 ">
      <p>
        <%= message.content %>
      </p>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit button_text %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <%= user.name %>
  </p>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/new.html.erb
<div class="container mx-auto text-center mt-20">
  <div class="shadow-xl rounded w-3/4 max-w-xl mx-auto p-8 border-gray-300 bg-white">
    <h1 class="text-2xl">ようこそ</h1>
    <p class="mt-24">どこかのだれかと2人でチャットできます</p>

    <%= form_with(model: @user) do |form| %>
      <div class="mt-32 w-3/4 mx-auto">
        <%= form.label :name, class: "text-left text-sm display block" %>
        <%= form.text_field :name, class: "mt-2 border-gray-400 rounded rounded w-full" %>
      </div>

      <div class="actions">
        <%= form.submit 'はじめる', class: "mt-24 bg-blue-600 py-2 px-4 rounded text-gray-50" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", user_path(@user), method: :delete %>
</div>